// <auto-generated />
namespace CharcoalCompanion.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class specifiesSteps : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(specifiesSteps));
        
        string IMigrationMetadata.Id
        {
            get { return "202007010036124_specifiesSteps"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
